image: python:3.10

stages:
  - install
  - test
  - train
  - validate

before_script:
  - python --version
  - python -m pip install --upgrade pip

install_dependencies:
  stage: install
  script:
    - python -m pip install -r requirements.txt

test_model:
  stage: test
  script:
    - echo "Skipping tests for now"

train_model:
  stage: train
  script:
    - python _helloworld.py

validate_model:
  stage: validate
  script:
    - echo "Validation done"
